# Generated by Django 3.2.11 on 2024-03-03 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channeldetail',
            name='country',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='channeldetail',
            name='default_audio_language',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='channeldetail',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='channeldetail',
            name='published_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='channeldetail',
            name='thumbnails',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='channeldetail',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='videodetail',
            name='actual_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='videodetail',
            name='actual_start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='videodetail',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.channeldetail'),
        ),
        migrations.AlterField(
            model_name='videodetail',
            name='default_audio_language',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='videodetail',
            name='published_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='videodetail',
            name='scheduled_start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='videodetail',
            name='thumbnails',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='videodetail',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
