# Generated by Django 3.2.11 on 2024-03-03 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='videodetail',
            table='video_detail',
        ),
    ]
