# Generated by Django 3.2.11 on 2024-03-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20240303_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(max_length=100)),
                ('video_id', models.CharField(max_length=100)),
                ('playlist_video_id', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField(null=True)),
                ('delete_flag', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'playlist_detail',
                'unique_together': {('playlist_id', 'playlist_video_id')},
            },
        ),
    ]
