services:
  api:
    container_name: api
    # 一旦docker-compose.ymlに書くためコメントアウト
    # build: ./docker/api
    # OpenJDKでもAmazon Correttoでもどっちでも
    image: amazoncorretto:11
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./spring-project:/srv:cached
    working_dir: /srv
  db:
    container_name: postgresql
    image: postgres:13.4
    # いるかわからん
    # restart: always
    ports:
      - 5432:5432
    environment:
    # TODO:環境変数から取得するように修正
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: