services:
  api:
    container_name: api
    # 一旦docker-compose.ymlに書くためコメントアウト
    # build: ./docker/api
    # OpenJDKでもAmazon Correttoでもどっちでも
    image: amazoncorretto:11
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./spring-project:/srv:cached
    working_dir: /srv
  view:
    container_name: view
    build: ./docker/view
    command: /bin/sh -c "if [ ! -e node_modules ]; then npm install --check-files; fi && npm run serve"
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./vue-project:/app:cached
    working_dir: /app/my-vue-app
  db:
    container_name: postgresql
    image: postgres:13.4
    # いるかわからん
    # restart: always
    ports:
      - 5432:5432
    environment:
      # TODO:環境変数から取得するように修正
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # 初期データ投入用
      - ./docker/db/scripts:/docker-entrypoint-initdb.d
      - ./docker/db/sql:/sql
volumes:
  postgres_data:
